### ISSUE TITLE
tutorial suggestion

### ISSUE THREAD

**Issue by fbrau** [nitrogen/NitrogenProject.com#10]
Don't know if this is the right channel but wanted to note the tutorial could have 
a note on the my_element.erl example about suggesting to declare event/1 to export.
New erlang and nitrogen users will get stuck on this...

**Comment by choptastic** [comment]
Good call! Thank you!

On Sun, May 15, 2016 at 11:39 PM, fbrau <notifications@github.com> wrote:

> Don't know if this is the right channel but wanted to note the tutorial
> could have
> a note on the my_element.erl example about suggesting to declare event/1
> to export.
> New erlang and nitrogen users will get stuck on this...
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/nitrogen/NitrogenProject.com/issues/10>
>



-- 
Jesse Gumm
Owner, Sigma Star Systems
414.940.4866 || sigma-star.com || @jessegumm
